### ISSUE TITLE
EDA on the new loop data

### ISSUE THREAD

**Issue by vadimnazarov** [antigenomics/tcr-pmhc-study#10]
Split to test / train / CV + plot them

**Comment by vadimnazarov** [comment]
Split to equal number of real / putative CDRs

**Comment by vadimnazarov** [comment]
Split to equal number of "upside" and "downside" peptides for the training.

Check if "downsides" are "downsode" for both X and Y coordinates.

**Comment by mikessh** [comment]
1. I prefer to treat MHC peptides separately, selecting peptide/antigen features that influence orientation wrt tcr-mhc axis
2. It can pay off if we first select representative profiles using unsupervised clustering
3. I would be really happy if we can outline loop/peptide length as a continuous parameter rather than fitting a model for every length
